// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCU93wkp-rJJzjsv4GEo0hV503emEzeIvA',
    appId: '1:290985653432:web:24c163cc5677477f42704d',
    messagingSenderId: '290985653432',
    projectId: 'hotelapp-e8011',
    authDomain: 'hotelapp-e8011.firebaseapp.com',
    storageBucket: 'hotelapp-e8011.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArUQQTPU566YedNb1srTZethAolmMvPP8',
    appId: '1:290985653432:android:e704ef473d15364642704d',
    messagingSenderId: '290985653432',
    projectId: 'hotelapp-e8011',
    storageBucket: 'hotelapp-e8011.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgQ5NGJEXJ01Rb8BsTnMrIKYLeqmXAa14',
    appId: '1:290985653432:ios:90eb492fd5e6a10b42704d',
    messagingSenderId: '290985653432',
    projectId: 'hotelapp-e8011',
    storageBucket: 'hotelapp-e8011.appspot.com',
    iosBundleId: 'com.example.hotelVendor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgQ5NGJEXJ01Rb8BsTnMrIKYLeqmXAa14',
    appId: '1:290985653432:ios:cb3d543a0556543f42704d',
    messagingSenderId: '290985653432',
    projectId: 'hotelapp-e8011',
    storageBucket: 'hotelapp-e8011.appspot.com',
    iosBundleId: 'com.example.hotelVendor.RunnerTests',
  );
}
